spring.application.name=product-service

server.port=8080

spring.datasource.url=jdbc:postgresql://ecommerce-postgres:5432/ecommerce
spring.datasource.username=ecommerceuser
spring.datasource.password=EcomPass2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always